### ISSUE TITLE
Both Taskbars appear on one monitor after waking Mac from sleep

### ISSUE THREAD

**Issue by Surrylic** [lawand-dot-io/taskbar#217]
The taskbar for both the left and right monitor appear on the left monitor when waking the computer from sleep. The taskbar from the right monitor (which appears floating mid-screen on the left) is not able to be clicked or moved in any way. I have to kill the app and reopen to resolve. There is no taskbar on the right monitor. Using the latest MacOS 26 beta.

**To Reproduce**
1. Use two monitors. Be on MacOS26.
2. Allow computer and monitors to go into sleep mode.
3. Upon waking and unlocking machine, both taskbars are on one screen.

**Desktop (please complete the following information):**
 - Taskbar 1.4.6
 - OS: macOS 26
 - Chip: M2 (Mac mini)

<img width="1779" height="624" alt="Image" src="https://github.com/user-attachments/assets/9186998d-a721-421f-bd1a-8b1aa1546940" />

**Comment by Surrylic** [comment]
You’re welcome! I mostly made a point to submit this due to it happening on macOS 26. I hoped it would be helpful so you don’t get a wave of reports in a month. So far it’s the only issue I’ve seen.

**Comment by lawand-dot-io** [comment]
And by the way I know that the launchpad button no longer works. I'm planning to replace it with my own start menu as a solution :)

**Comment by lawand-dot-io** [comment]
Hello, are you still having this bug? I tried it with the official macOS 26.0 and it's not happening for me, I'm gonna keep trying but I thought I would ask you first if you are seeing this with macOS 26.0 or is this fixed at this point and it was a macOS beta bug? Thanks

**Comment by Surrylic** [comment]
Yup still have the bug. It's not every time, but _most_ of the time I guess. I don't know anything about anything, but I'd guess it's a difference between our monitors or Macs causing you not to see it.

**Comment by lawand-dot-io** [comment]
I see, I was trying it only using the MacBooks own monitor as well as one external monitor, I'm gonna try with two external monitors

**Comment by lawand-dot-io** [comment]
Hey, I'm assuming this bug is still happening? One idea is that you can perhaps try the [Beta version of taskbar](https://x.com/lawand_dot_io/status/1974647885456372118) since it includes several bug fixes and maybe one of them will fix this bug

**Comment by Surrylic** [comment]
Yes sir, the bug is still happening as of yesterday. I've installed the beta version now, and will keep you updated. I don't have much of a work day today, but I should know by early next week if not sooner if this works or not. Thanks for your continued work 👍

**Comment by lawand-dot-io** [comment]
Great, let me know whenever you can, no hurry

**Comment by Surrylic** [comment]
When my computer woke from sleep this morning I had both taskbars on one screen again. Sorry!

**Comment by lawand-dot-io** [comment]
@Surrylic no worries, thanks for the information. I am hoping that one of the upcoming updates of macos 26 will solve this problem if it was a macOS bug, so let's see. And in the meantime I will keep trying to reproduce the bug locally so that I can start to understand what is causing it. Out of curiosity when the bug happens, are you using the laptop screen plus one external monitor or is it just two external monitors. If it is two monitors do they have the same size and same resolution?

**Comment by Surrylic** [comment]
Two external monitors, same size and resolution (5k). I use an M2 Mac Mini.

**Comment by lawand-dot-io** [comment]
OK thanks

**Comment by lawand-dot-io** [comment]
I have tried a lot to reproduce this bug without success, I'm fairly confident at this point that this is a macos 26 bug where the operating system is not notifying taskbar about the second screen, I think one way to be sure about this is that the next time you have the bug, If it's not too inconvenient try to disconnect one of the two screens and then reconnect it and I'm sure that at that point both taskbars will appear correctly. This might be good to know because that you can avoid restarting taskbar which leads to resetting the order of the windows in taskbar in case that was important for you. Let's hope that one of the upcoming updates of macOS fixes this issue and I will keep trying to reproduce the bug. Also if you were able to verify my understanding of the bug as I mentioned above then maybe if this bug does not get fixed by macOS I might eventually add some kind of a temporary fix that periodically checks for changes in the screens

**Comment by Surrylic** [comment]
Wouldn't be surprised if it's a macOS 26 bug. And I'm happy to troubleshoot as much as you'd like! I unplugged the left monitor and it just moved the two taskbars to the right monitor haha. I plugged it back in, and then unplugged the right and overall same effect. No matter what I unplug and plug back in I still see two taskbars on one screen once the bug happens.

Is there anything I can do to provide any debug info to you?

**Comment by lawand-dot-io** [comment]
Thank you very much for offering to help with this, I will probably need your help to debug the issue. There is a way for you to give me debug logs, but let's wait first for version 26.1 which should be released soon and let's see if the bug is not fixed from their side

**Comment by lawand-dot-io** [comment]
@Surrylic have you updated to 26.1 yet? Am I lucky enough that this bug has been fixed in 26.1?

**Comment by lawand-dot-io** [comment]
And by the way if the bug is still happening then we should start to debug it. If so, let me know if you are using Taskbar 1.5.0 (with start menu) or the previous version so that I create a custom build that will help me debug the problem, thanks

**Comment by Surrylic** [comment]
Good morning sorry for my slow reply. I’m using macOS 26.2 now (been on the dev beta) and the bug is still occurring. I’m using the version with the start menu, which I love btw. Great implementation on that!

**Comment by Surrylic** [comment]
Soooo... not great news - one of my monitors died, so I'm stuck with a single monitor for the foreseeable future. I won't be able to test this afterall :/

**Comment by lawand-dot-io** [comment]
Oh, I'm sorry to hear about your monitor. Yeah, I also tried to test this on my laptop and I bought a second Monitor but then I realize that MacBook Air only allows connecting to one monitor haha, so I still haven't figured out how to debug this issue, but I am very confident that this is a macOS bug and I hope they fix it in one of the upcoming updates. In any case I will keep this issue open and maybe try to get my hand on a Mac mini to debug it. Anybody else reading this, if you can help with the debugging let me know. Thanks

**Comment by lawand-dot-io** [comment]
Based on some initial testing, I don't see the bug happening in the latest version of macos 26, so I suspect that this was a macos 26 bug and it is now fixed. If somebody is still having this issue please comment here and mention which version of macOS 26 do you have, thanks

**Comment by lawand-dot-io** [comment]
Update: I think I figured out a fix for this bug. Anybody interested in beta testing you can see the link below. I would really appreciate if somebody can confirm that this fixes the bug, thanks. To install, quit Taskbar then unzip this version and move the file inside into the applications folder (and overwrite the existing one) and then run it from there

https://www.dropbox.com/scl/fi/pdofjvzubyd484ll8lnjl/Taskbar-1.6.6.zip?rlkey=jfgpciabz8pav38p7o60hyxg3&st=po5ty8sz&dl=1

**Comment by Surrylic** [comment]
I really hope the other person seeing this issue can test, because unfortunately I'm still stuck using one monitor ever since my second one broke. I still love the app and always use it, though!

**Comment by lawand-dot-io** [comment]
Sorry to hear about your monitor, I'm glad that you still find Taskbar useful 👍
